// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5JJG1Xe6jWZsv_qDyee25mbmIdnHsSC4',
    appId: '1:560356734084:web:4da450bf40e1a71829fed1',
    messagingSenderId: '560356734084',
    projectId: 'car-rental-yobernu',
    authDomain: 'car-rental-yobernu.firebaseapp.com',
    storageBucket: 'car-rental-yobernu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8pAUUK7J5gFfJAIWJT0hZdMmqnqSSq5k',
    appId: '1:560356734084:android:7f5a47448174755e29fed1',
    messagingSenderId: '560356734084',
    projectId: 'car-rental-yobernu',
    storageBucket: 'car-rental-yobernu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq8Jvd016uVMZpXH44vb_akFkcPFqr1t8',
    appId: '1:560356734084:ios:7f3b18089ca61bac29fed1',
    messagingSenderId: '560356734084',
    projectId: 'car-rental-yobernu',
    storageBucket: 'car-rental-yobernu.firebasestorage.app',
    iosBundleId: 'com.example.starterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq8Jvd016uVMZpXH44vb_akFkcPFqr1t8',
    appId: '1:560356734084:ios:7f3b18089ca61bac29fed1',
    messagingSenderId: '560356734084',
    projectId: 'car-rental-yobernu',
    storageBucket: 'car-rental-yobernu.firebasestorage.app',
    iosBundleId: 'com.example.starterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5JJG1Xe6jWZsv_qDyee25mbmIdnHsSC4',
    appId: '1:560356734084:web:e6fc08e1f31c3a0729fed1',
    messagingSenderId: '560356734084',
    projectId: 'car-rental-yobernu',
    authDomain: 'car-rental-yobernu.firebaseapp.com',
    storageBucket: 'car-rental-yobernu.firebasestorage.app',
  );
}
